quizfun/prediction/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
#from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'prediction', views.prediction, name='prediction'),
    url(r'^bet/(?P<prediction_id>\d+)/$', views.bet, name='bet'),
    url(r'^save_bet', views.save_bet, name='save_bet'),
    url(r'^my_bets', views.my_bets, name='my_bets'),
]

quizfun/quizfun/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('userprofile.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^', include('question.urls')),
    url(r'^', include('notification.urls')),
    url(r'^', include('prediction.urls')),
    url(r'^', include('ranking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizfun/ranking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^ranking', views.global_ranking, name="ranking"),
    url(r'^monthly_ranking', views.monthly_ranking, name="monthly_ranking"),
]

quizfun/prediction/models.py
from django.db import models
from question.models import Category
from userprofile.models import UserProfile
from django.forms import ValidationError
import datetime
from django.utils import timezone


class Prediction(models.Model):
    description = models.CharField(max_length=200)
    category = models.ForeignKey(Category)
    date_started = models.DateTimeField(auto_now_add=True,blank=False)
    finish_bet_date = models.DateTimeField(blank=False)
    finish_pred = models.DateTimeField(blank=False)

    def __str__(self):
        return self.description


class PredOption(models.Model):
    prediction = models.ForeignKey(Prediction)
    description = models.CharField(max_length=200)
    probability = models.DecimalField(max_digits=4, decimal_places=2,
                                      default=1.00)
    is_correct = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.description

    def clean(self):
        if self.probability <= 1.00:
            raise ValidationError('Put a positive and significant probability')
        if self.prediction:
            if self.prediction.finish_pred > timezone.now() and self.is_correct:
                raise ValidationError('You cant upload the correct answer yet')


class OptionBet(models.Model):
    userprofile = models.ForeignKey(UserProfile)
    optionbet = models.ForeignKey(PredOption)
    amount_bet = models.IntegerField()


def notify_pred_load(id_prediction):
    from notification.models import Notification
    from prediction.models import Prediction, PredOption, OptionBet
    tupla_options = PredOption.objects.filter(prediction=id_prediction)
    for op in tupla_options:
        tupla_users_optbet = OptionBet.objects.filter(optionbet=op)
        for us in tupla_users_optbet:
            if op.is_correct:
                us.userprofile.add_coins(op.probability * us.amount_bet)
                n = Notification(description='Response to ' + op.description +
                                 ' has already been loaded, you won '
                                 + str(op.probability * us.amount_bet)
                                 + ' coins!', profile=us.userprofile)
                n.save()
            else:
                n = Notification(description='Response to ' + op.description +
                                 ' has already been loaded, you lost ' +
                                 str(us.amount_bet) + ' coins!',
                                 profile=us.userprofile)
                n.save()

quizfun/question/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import datetime
from django.utils import timezone
# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=60, unique=True)

    def __str__(self):
        return self.category_name


class Difficulty(models.Model):
    difficulty = models.CharField(max_length=60, unique=True)

    max_reward = models.IntegerField(default=0)
    min_reward = models.IntegerField(default=0)
    max_loss = models.IntegerField(default=0)
    min_loss = models.IntegerField(default=0)

    def __str__(self):
        return self.difficulty


class Question(models.Model):
    description = models.CharField(max_length=200, unique=True)
    category = models.ForeignKey(Category)
    reward_coins = models.IntegerField(default=0)
    loss_coins = models.IntegerField(default=0)
    difficulty = models.ForeignKey(Difficulty)
    time_limit = models.IntegerField(default=5)

    def __str__(self):
        return self.description

    def clean(self):
        super(Question, self).clean_fields()
        max_reward = self.difficulty.max_reward
        min_reward = self.difficulty.min_reward

        max_loss = self.difficulty.max_loss
        min_loss = self.difficulty.min_loss

        if (self.reward_coins < min_reward) or (self.reward_coins >
                                                max_reward):
            raise ValidationError('Invalid coins! Remember '
                                  'that the acceptable range '
                                  'of the award is: '
                                  + str(max_reward) + ' - ' + str(min_reward))
        elif (self.loss_coins < min_loss) or (self.loss_coins > max_loss):
            raise ValidationError('Invalid coins! Remember '
                                  'that the acceptable range '
                                  'the loss is :' + str(max_loss) +
                                  ' - ' + str(min_loss))
        elif (self.time_limit < 5):
            raise ValidationError('Invalid time limit! remember '
                                  'that time must be greater than '
                                  'or equal to 5')


class Answer(models.Model):
    question = models.ForeignKey(Question)
    description = models.CharField(max_length=200)
    is_correct = models.BooleanField()

    def __str__(self):
        return self.description


class Solved(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)


class QuestionStarted(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    updated = models.DateTimeField(auto_now_add=True)

    def remaining_time(self):
        time = self.question.time_limit
        time_now = datetime.now(timezone.utc)
        return time - int((time_now - self.updated).total_seconds())

quizfun/ranking/models.py
from django.db import models

# Create your models here.

quizfun/prediction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Prediction, PredOption, OptionBet
from datetime import datetime
from django.utils import timezone
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

def admin_check(user):
    return (not user.is_superuser)

@user_passes_test(admin_check,login_url='/',redirect_field_name=None)
@login_required(login_url='/login')
def prediction(request):
    profile = request.user.userprofile
    if (profile.coins >= 1):
        p = Prediction.objects.filter(finish_bet_date__gte=datetime.now(timezone.utc))
        p_list = []
        for x in p:
            p_list.append(x)
        my_bets = OptionBet.objects.filter(userprofile=profile)
        bet_list = []
        for b in my_bets:
            bet_list.append(b.optionbet.prediction)
        pred = set(p_list) - set(bet_list)
        return render(request, "prediction.html",{'predictions': pred})
    else:
        messages.error(request, 'You don\'t have enough coins :(')
        return redirect('index')

@user_passes_test(admin_check,login_url='/',redirect_field_name=None)
@login_required(login_url='/login')
def bet(request, prediction_id):
    p = get_object_or_404(Prediction,pk=prediction_id)
    if (p.finish_bet_date > datetime.now(timezone.utc)):
        p_options = PredOption.objects.filter(prediction = prediction_id)
        p_options_list = []
        for x in p_options:
            p_options_list.append(x)
        return render(request, 'bet.html', {'prediction': p, 'p_options_list': p_options_list})
    else:
        messages.error(request, 'This prediction has alredy expired')
        return redirect('index')

@user_passes_test(admin_check,login_url='/',redirect_field_name=None)
@login_required(login_url='/login')
def save_bet(request):
    if request.POST:
        profile = request.user.userprofile
        selected_option = PredOption.objects.get(pk=request.POST['selected'])
        amount_bet = int(request.POST['bet'])
        option = OptionBet(userprofile=profile,optionbet=selected_option,amount_bet=amount_bet)
        option.save()
        profile.sub_coins(amount_bet)
        data = {
            'status' : True
        }
        messages.success(request, 'Your bet has been saved. Your coins will be detain :)')
    return redirect('index')

@user_passes_test(admin_check,login_url='/',redirect_field_name=None)
@login_required(login_url='/login')
def my_bets(request):
    profile = request.user.userprofile
    my_bets = OptionBet.objects.filter(userprofile = profile)
    context = {'my_bets': my_bets}
    return render(request, 'my_bets.html', context)

quizfun/quizfun/views.py
from django.http import HttpResponse
from django.shortcuts import render
from userprofile.models import UserProfile


def index(request):
    return render(request, 'index.html')

quizfun/ranking/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User
from userprofile.models import UserProfile

def global_ranking(request):
    ranking = UserProfile.objects.all().order_by('-coins')
    rank_list = []
    for x in ranking:
    	if not x.user.is_superuser:
    		rank_list.append(x)
    context = {'ranking': rank_list}
    return render(request, 'ranking.html', context=context)

def monthly_ranking(request):
	ranking = UserProfile.objects.all().order_by('-balance')
	rank_list = []
	for x in ranking:
		if not x.user.is_superuser:
			rank_list.append(x)
		context = {'ranking': rank_list}
	return render(request, 'monthly_ranking.html', context=context)

quizfun/quizfun/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Quiz Fun</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<!-- Ubicacion CSS -->
	<link rel="stylesheet" href="{% static 'css/quizfun.css' %}">
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-to">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'index'%}">Quiz Fun</a>
			</div>
			<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
						{% if user.is_superuser %}
							<li><a href="admin/">Admin site</a></li>
							<li><a href="#" data-toggle="modal" data-target="#logoutModal"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
						{% else %}
					    	<p class="navbar-text">Coins: {{user.userprofile.coins}}</p>
					    	<li><a href="{% url 'list_notification'%}"><span class="glyphicon glyphicon-bell"></span> Notification ({{ user.userprofile.amount_notifications }})</a></li>
							<li class="dropdown">
								<a class="navbar-left dropdown-toggle" data-toggle="dropdown" href="#">
							    {% if user.userprofile.avatar == "" %}
							    	<img src="media/useravatars/default.jpg" height="20px"> {{user}} <span class="caret"></span>
						    	{% else %}
						    		<img src={{ user.userprofile.avatar.url }} height="20px"> {{user}} <span class="caret"></span>
						    	{% endif %}
								</a>
								<ul class="dropdown-menu">
						    		<li><a href="{% url 'profile_user'%}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
										<li><a href='/ranking'><span class="glyphicon glyphicon-globe"></span> Global Ranking</a></li>
										<li><a href='/monthly_ranking'><span class="glyphicon glyphicon-circle-arrow-up"></span> Monthly Ranking</a></li>
						        <li><a href="#" data-toggle="modal" data-target="#logoutModal"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
								</ul>
						     </li>
			    		{% endif %}
							<!-- Cuadro de dialogo de cerrar sesion -->
							<div class="modal" id="logoutModal" tabindex="-1" role="dialog" aria-hidden="true">
							  <div class="modal-dialog modal-sm">
							    <div class="modal-content">
							      <div class="modal-header">
							        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
							        <h4> Log out <i class="fa fa-lock"></i></h4>
							      </div>
							      <div class="modal-body">
							        <p><i class="fa fa-question-circle"></i> ¿Are you sure to logout? <br/><br></p>
							        <div class="actionsBtns">
							            <form action="/logout" method="post">
							                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
												<a href="{% url 'logout'%}" class="btn btn-primary" role="button">Logout</a>
								                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
							            </form>
							        </div>
							      </div>
							    </div>
							  </div>
							</div>
			    	{% else %}
			    	<li><a href="{% url 'register_user'%}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
					<li><a href="{% url 'login'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
			    {% endif %}
		    </ul>
		</div>
	</nav>


		{% block content %}
		{% endblock %}

	    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
	    <script src="{% static 'js/app.js' %}"></script>
    	{% block javascript %}{% endblock %}
	</body>
</html>

quizfun/quizfun/templates/bet.html
{% extends 'base.html' %}
{% block javascript %}
<script>
  $("input[name='option-sel']").change(function(){
    console.log($(this).val());
    $('input:not(:checked)').siblings().removeClass("option-selected");
    $('input:checked').siblings().addClass("option-selected");
    $("input[name='selected']").val($(this).val())
    $("input[name='res']").val($(this).siblings('label').attr('value'))
  });

  $('button').on('click',function(event){
        if ($('input:checked').val()===undefined){
            return false
        }
        else {
            return true
        }
    });

</script>
{% endblock %}
{% block content %}

<div class="container">
  <h1> Prediction: {{prediction.description}}</h1>
  <hr>
    <table class="table table-striped">
      <thead>
        <tr class="info">
          <th>Options</th>
          <th>Probability</th>
        </tr>
      </thead>
      <tbody>
        {%for p in p_options_list %}
          <tr class="warning">
            <td><input type="radio" name="option-sel" id="option-sel{{ forloop.counter }}" value="{{ p.id }}" style="display: none"><label class="option" for="option-sel{{ forloop.counter }}" value="{{p.description}}">{{p.description}}</label></td>
            <td>{{p.probability}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <form action='/save_bet' method="POST" id="pred-form">
    {% csrf_token %}
      <input type="text" name="selected" readonly style="display: none">
      <input type="text" name="res" readonly>
      <input type="number" name="bet" value='1' min="1" max="{{user.userprofile.coins}}">
      <br>
    <button type="submit">Select</button>
  </form>
  <a href="/prediction/">Back</a>
</div>
{% endblock %}

quizfun/quizfun/templates/change_password.html
{% extends 'base.html' %}
{% block content %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div class="container">
	<div class="login-page">
		<div class="form">
			<h2>Change Password</h2>
			<div class="change">
				<form class="login-form" method="post">
					{% csrf_token %}
					{{ form.as_p }}
					<button type="submit" class="save btn btn-default">Apply Changes</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

quizfun/quizfun/templates/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="login-page">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
		<div class="form">
			<h1>Edit Profile</h1>
    		<form class="login-form" action="/edit_profile" method="post" enctype='multipart/form-data'>
			    {% csrf_token %}
			    {{ form.as_p }}
    			<button type="submit" class="save btn btn-default">Apply Changes</button>
    		</form>
		</div>
	</div>
</div>
{% endblock %}

quizfun/quizfun/templates/get_question.html
{% extends 'base.html' %}

{% block javascript%}
<script>

    $(window).ready(function() {
        resetForm();
        setTimeout(countdown,1000);
    });

    $('button').on('click',function(event){
        if ($('input:checked').val()===undefined){
            return false
        }
        else {
            return true
        }
    });
    
    $('input[name="answer"]').change(function() {
        $('input:not(:checked)').siblings().removeClass("selected");
        $('input:checked').siblings().addClass("selected");
    });

    $('#question-form').on('submit', function (event) {
        event.preventDefault();
        var input = $("input")
        var del = $(this)
        var checked = $('input:checked')
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                dataType: 'json',
                success: function (data) {
                    if (data.vacio) {
                        return;
                    }
                    clearInterval(timeoutMyOswego);
                    del.children('.box').remove();
                    input.prop('disabled', true);
                    if (data.resp) {
                        $('.resp').append('<p class="right">Thas\'s right!<br/>You win {{pregunta.reward_coins}} coins</p>');
                        checked.siblings().removeClass("selected")
                        checked.siblings().toggleClass("right")
                    }
                    else {
                        $('.resp').append('<p class="wrong">Wrong! :(<br/>You lose {{ pregunta.loss_coins }} coins</p>');
                        checked.siblings().removeClass("selected")
                        checked.siblings().toggleClass("wrong")
                    }
                    setTimeout(function(){
                    $('.select').append('<button class="box next" onclick="location.reload()">Next Question</button>');
                    $('.select').append('<button class="box exit" onclick="goIndex()">Exit question mode</button>');
                    },1000);
                }
            });
    });
    function noTime() {
        $('input:checked').siblings().removeClass("selected");
        resetForm();
        $('#question-form').submit();
        $("input").prop('disabled', true);
        $("#question-form").children('.box').remove();
        $("#question-form").children('input[name="answer"]').remove();
        $('.resp').append('<p class="wrong">Time Out!<br/>You lose {{ pregunta.loss_coins }} coins</p>');
        setTimeout(function() {
        $('.select').append('<button class="box next" onclick="location.reload();resetForm()">Next Question</button>')
        $('.select').append('<button class="box exit" onclick="goIndex()">Exit question mode</button>');
        },1000);
    }


</script>

{% endblock %}

{% block content %}


<div class="container">
    <div class="quiz-container">
        <div class="question box">
            <h3><div id="countdown">{{ time_left }}</div></h3>
            <h1>{{ pregunta.description }}</h1>
            <p>Difficulty: {{ pregunta.difficulty }}</p>
            <p>Category: {{ pregunta.category }}</p><br/>
            <p class="coins">Reward Coins: {{ pregunta.reward_coins }}</p>
            <p class="coins">Loss Coins: {{ pregunta.loss_coins }}</p>
        </div>
        <form action="/check_answer" method="POST" id="question-form">
            {% csrf_token %}
            {% for answer in pregunta.answer_set.all %}
                <ul class="answers">
                    <li class="answer">
                        <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" style="display: none">
                        <label class="la" for="answer{{ forloop.counter }}">
                            <p><span>{{ forloop.counter }}</span>{{ answer.description }}</p>
                        </label><br>
                    </li>
                </ul>
            {% endfor %}
            <button class="box" name="btnsubmit">Selection</button>
            <div class="resp"></div>
        </form>
        <div class="select"></div>
    </div>
</div>
{% endblock %}

quizfun/quizfun/templates/index.html
{% extends 'base.html' %}
{% block content %}

{% if messages %}
<div class="alert alert-info" role="alert">
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
</div>
{% endif %}
<br>
<br>
<div class="container">
  <h1 class="row skew-title">
    <span>W</span><span>E</span><span>L</span><span>C</span><span>O</span><span>M</span><span class="last">E</span>
    &nbsp;
    <span>T</span><span class="last">O</span>
    &nbsp;
    <span class="alt">Q</span><span class="alt">U</span><span class="alt">I</span><span class="alt">Z</span><span class="alt">F</span><span class="alt">U</span><span class="alt last">N</span>
  </h1>
</div>
<br>

<div class="container">
	{% if user.is_authenticated %}
		<div class="modes">
			{% if not user.is_superuser %}
				<div class="mode" onclick="window.location.href='/get_question'">
					<img src="media/useravatars/quiz.png"><!-- image quiz -->
					<div class="overlay">
						<div class="proximamente">Question mode</div>
					</div>
				</div>
				<div class="mode" onclick="window.location.href='/prediction'">
					<img src="media/useravatars/pred.png"><!-- image prediction-->
					<div class="overlay">
						<div class="proximamente">Prediction mode<br/><br/>Coming soon!</div>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-sm-6"><span class='containerg pulse-button1' onclick="window.location.href='/ranking'">Global Ranking</span></div>
					<div class="col-sm-5">	<span class='containerg pulse-button2' onclick="window.location.href='/monthly_ranking'">Monthly Ranking</span></div>
					</div>
			{% endif%}
		</div>
	{% else %}
	{% endif %}
</div>

<style>
.containerg {
width: 200px;
height: 100%;
-webkit-perspective: 1000;
-webkit-backface-visibility: hidden;
}

.pulse-button1 {
	display: inline-block;
	width: 200px;
	height: 100px;
	font-size: 1.3em;
	font-weight: light;
	font-family: 'Trebuchet MS', sans-serif;
	text-transform: uppercase;
	text-align: center;
	line-height: 100px;
	letter-spacing: -1px;
	color: white;
	border: none;
	border-radius: 10%;
	background: #003471;
	cursor: pointer;
	box-shadow: 0 0 0 0 rgba(90, 153, 212, 0.5);
	-webkit-animation: pulse 1.5s infinite;
}
.pulse-button2 {
	display: inline-block;
	width: 200px;
	height: 100px;
	font-size: 1.3em;
	font-weight: light;
	font-family: 'Trebuchet MS', sans-serif;
	text-transform: uppercase;
	text-align: center;
	line-height: 100px;
	letter-spacing: -1px;
	color: white;
	border: none;
	border-radius: 10%;
	background: #EE2323;
	cursor: pointer;
	box-shadow: 0 0 0 0 rgba(90, 153, 212, 0.5);
}

</style>

{% endblock %}

{% block javascript%}

<script>
(function() {
  $('.skew-title').children('span').hover((function() {
    var $el, n;
    $el = $(this);
    n = $el.index() + 1;
    $el.addClass('flat');
    if (n % 2 === 0) {
      return $el.prev().addClass('flat');
    } else {
      if (!$el.hasClass('last')) {
        return $el.next().addClass('flat');
      }
    }
  }), function() {
    return $('.flat').removeClass('flat');
  });
}).call(this);
</script>

{% endblock %}

quizfun/quizfun/templates/list_notification.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h1>User Notifications</h1>
    <br>
    <h4> Not Viewed </h4>
    <table class="table table-striped">
        <thead>
            <tr class="info">
                <th> <p>Description</p> </th>
                <th> <p>Date</p> </th>
            </tr>
        </thead>
        <tbody>
            {% if no_vistos %}
                {%for n in no_vistos %}
                    <tr class="warning">
                        <td>{{n.description}}</td>
                        <td>{{n.time}}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr class="warning">
                    <td>No new messages</td>
                    <td></td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    <hr>
    <h4> Viewed </h4>
    <table class="table table-striped">
        <thead>
            <tr class="info">
                <th> <p>Description</p> </th>
                <th> <p>Date</p> </th>
            </tr>
        </thead>
        <tbody>
            {% if vistos %}
                {%for n in vistos %}
                    <tr class="warning">
                        <td>{{n.description}}</td>
                        <td>{{n.time}}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr class="warning">
                    <td>No messages</td>
                    <td></td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

{% endblock %}

quizfun/quizfun/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="login-page">
    <div class="form">
      <h2>Login</h2>
      {% if user.is_authenticated %}
 	    	You are logged in already!
 	    {%else%}
        <form class="login-form" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Login</button>
        </form>
      {%endif%}
    </div>
  </div>
</div>
{% endblock %}

quizfun/quizfun/templates/my_bets.html
{% extends 'base.html' %}
{% block content %}

<body>

<div class="container">
  <h2>My bets</h2>
  <table class="table table-striped">
    <thead>
      <tr class="info">
        <th>Prediction</th>
        <th>Option Selected</th>
        <th>Amount bet</th>
      </tr>
    </thead>
    <tbody>
      {% if my_bets %}
     {%for n in my_bets %}
     <tr class="warning">
       <td>{{n.optionbet.prediction}}</td>
       <td>{{n.optionbet}}</td>
       <td>{{n.amount_bet}}</td>
    </tr>
    {% endfor %}
  {% else %}
    <tr class="warning">
      <td>You don't have bets yet.</td>
      <td></td>
      <td></td>
  </tr>
    {% endif %}
    </tbody>
  </table>
</div>
</body>
</html>

{% endblock %}

quizfun/quizfun/templates/register.html
{% extends 'base.html' %}
{% block content %}
	<div class="login-page">
    {% if profile_form.errors %}
        {% for field in profile_form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in profile_form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
		<div class="form">
			<h2>Register</h2>
			<form method="POST" class="login-form post-form" enctype="multipart/form-data">{% csrf_token %}
				{{ profile_form.as_p}}
				<button type = "submit" class="save btn btn-default">Sign up</button>
			</form>
		</div>
	</div>
{% endblock %}